
au InsertEnter * set cul
au InsertLeave * set nocul

call plug#begin('~/.vim/plugged')
Plug 'puremourning/vimspector'
Plug 'neoclide/coc.nvim', {'branch': 'release'}
Plug 'junegunn/fzf', { 'do': { -> fzf#install() } }
Plug 'junegunn/fzf.vim'
Plug 'preservim/nerdtree'
Plug 'itchyny/lightline.vim'
Plug 'mxw/vim-jsx'
Plug 'pangloss/vim-javascript'
Plug 'leafgarland/typescript-vim'
Plug 'peitalin/vim-jsx-typescript'
Plug 'turbio/bracey.vim', {'do': 'npm install --prefix server'}
Plug 'tpope/vim-fugitive'
Plug 'mattn/emmet-vim'
Plug 'vim-test/vim-test'
call plug#end()

set termguicolors
" colorscheme catppuccin_mocha

" Key mappings
nnoremap <C-p> :Files<CR>
nnoremap <C-n> :NERDTreeToggle<CR>
nnoremap <Leader>rg :Rg<CR>
nnoremap <Leader>dd :Vimspector#Launch<CR>
nnoremap <Leader>ds :Vimspector#Reset<CR>
nnoremap <Leader>db :Vimspector#ToggleBreakpoint<CR>
nnoremap <Leader>dc :Vimspector#Continue<CR>
nnoremap <Leader>dn :Vimspector#StepOver<CR>
nnoremap <Leader>di :Vimspector#StepInto<CR>
nnoremap <Leader>do :Vimspector#StepOut<CR>
nnoremap <Leader>bs :!browser-sync start --server --files "src/**/*" --port 3000<CR>
nnoremap <Leader>bc :!open -a "Google Chrome" http://localhost:3000<CR>
nnoremap <Leader>t :TestFile<CR>
nnoremap <Leader>s :TestSuite<CR>
let g:user_emmet_leader_key='<C-e>'

" CoC and Prettier
inoremap <expr> <Tab> pumvisible() ? "\<C-n>" : "\<Tab>"
nmap <silent> gd <Plug>(coc-definition)
autocmd BufWritePre *.js,*.jsx,*.ts,*.tsx,*.html,*.css :CocCommand prettier.formatFile

" other
set endofline
