#!/bin/sh

sed -e 's/PermitRootLogin\ no/PermitRootLogin\ yes/g;s/PasswordAuthentication\ no/PasswordAuthentication\ yes/g' /etc/ssh/sshd_config > .tmpsshd_config 
cp .tmpsshd_config /etc/ssh/sshd_config
rm .tmpsshd_config
