#!/bin/sh

CSV="$1"

if [ $# -lt 1 ] ; then
  echo "usage: $0 file [csv_field]"; exit 1;
else
    if test -s "$1" ; then
      fields=`head -n2 "$CSV" | sed 1d | tr ' ' '_'`;
      echo "$fields"
    else
      echo "file DNE or is empty!"
      exit 1;
    fi

    if [[ "$2" != "" ]] && echo "$fields" | grep -q "$2" ; then
        arr_fields=(${fields//,/ })
        findfieldindex () {
            for field_for_index in `echo ${arr_fields[@]}` ; do
                if [[ "$field_for_index" == "$1" ]] ; then
                    break ;
                fi
                field_index=$(( $field_index + 1 ));
            done
        }
        field_index=0
        findfieldindex "$2"
        echo $(( $field_index + 1 ));
    fi
fi
