#!/bin/sh


for folder in ~/Documents/Articles /Users/Stephen/Documents/Bibliographies,\ Booklists,\ Syllabi ~/Documents/CUA-MA ~/Documents/CUA-Teaching ~/Documents/Greek\ Authors:Texts ~/Documents/LEC ~/Documents/Latin\ Authors:Texts ~/Documents/Lexica:Ref ~/Documents/PDF\ Library ~/Documents/vimwiki_textastic ~/Documents/Programming\ Docs ~/Documents/SysAdmin\ Docs 

do

sudo chown -R stephen "$folder"
sudo chgrp -R www "$folder"
sudo chmod -R g+w "$folder"

done
