#!/bin/sh

djvulist=( ./*.djvu )

for filename in "${djvulist[@]}"; do
	echo "processing $filename ..."
	outputname=`echo "$filename" | sed -e 's/djvu//g'`;
	/Applications/DjView.app/Contents/bin/ddjvu -format=tiff -mode=black -quality=100 "$filename" "$outputname"tiff 
	tiff2pdf -o"$outputname"pdf "$outputname"tiff 
	rm "$outputname"tiff
done
