#!/bin/bash
if [ $# -lt 1 ]
then
        echo "usage: $0 files_to_edit"; exit 1;
else
		HOST=`/bin/hostname`;
		for FILENAME in $@; do
			if [ "${FILENAME:0:1}" = "/" ] 
			then
				echo "ssh localhost -f -p 38383 '/opt/local/bin/mvim --remote-tab rsync://$HOST/$FILENAME'";
				ssh localhost -f -p 38383 '/opt/local/bin/mvim --remote-tab rsync://$HOST/$FILENAME';
			else
				ssh localhost -f -p 38383 '/opt/local/bin/mvim --remote-tab rsync://$HOST/$PWD/$FILENAME';
				echo "ssh localhost -f -p 38383 '/opt/local/bin/mvim --remote-tab rsync://$HOST/$PWD/$FILENAME'";
			fi	
		done 
fi
