#!/bin/sh
rsync --size-only -aPL --delete --exclude '.thumbnail' /Users/stephen/Documents/PDF\ Library/ /Volumes/Untitled/PDF\ Library/
rsync --size-only -aPL --delete --exclude '.thumbnail' /Users/stephen/Documents/ePub\ Books/ /Volumes/Untitled/ePub\ Books/

rsync --size-only -aPL --delete --exclude '.thumbnail' /Users/stephen/Documents/Greek\ Authors:Texts/Thucydides/ /Volumes/Untitled/Greek/Thucydides/
rsync --size-only -aPL --delete --exclude '.thumbnail' /Users/stephen/Documents/Greek\ Authors:Texts/Clement\ of\ Alexandria\ \(150-215\)/ /Volumes/Untitled/Greek/Clement\ of\ Alexandria\ \(150-215\)/
rsync --size-only -aPL --delete --exclude '.thumbnail' /Users/stephen/Documents/Greek\ Authors:Texts/Xenophon/ /Volumes/Untitled/Greek/Xenophon/

rsync --size-only -aPL --delete --exclude '.thumbnail' /Users/stephen/Documents/CUA-MA/Athenian\ Empire\ \(Thucydides\)\ GR587/ /Volumes/Untitled/CUA-MA/Athenian\ Empire/
rsync --size-only -aPL --delete --exclude '.thumbnail' /Users/stephen/Documents/CUA-MA/Latin\ Paleography\ LAT733/ /Volumes/Untitled/CUA-MA/Latin\ Paleography/
rsync --size-only -aPL --delete --exclude '.thumbnail' /Users/stephen/Documents/CUA-MA/Gregory\ of\ Nazianzus\ GR705/ /Volumes/Untitled/CUA-MA/Gregory\ of\ Nazianzus/


rsync --size-only -aPL --delete --exclude '.thumbnail' /Users/stephen/Documents/notes/ /Volumes/Untitled/notes/
rsync --size-only -aPL --delete --exclude '.thumbnail' /Users/stephen/Documents/notes_scholarly/ /Volumes/Untitled/notes_scholarly/

find /Volumes/Untitled -name '._*' -exec rm "{}" \;
find "/Volumes/Story HD" -name '._*' -exec rm "{}" \;
