#!/bin/sh
apikey=`cat ~/.tumblr-apikey`
alias json=/usr/local/share/npm/bin/json

latesturl=`curl -s "https://api.tumblr.com/v2/blog/altphi.tumblr.com/posts?api_key=${apikey}&limit=1" | json response.posts | json -ga post_url`;

echo "$latesturl"
