#!/usr/bin/env bash

if [[ "$1" == "mute-toggle" ]]; then
  wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle
  eww poll volume
  exit 0;
fi

if [[ "$1" == "up" ]]; then
  INC="0.1+"
else
  INC="0.1-"
fi

wpctl set-volume @DEFAULT_AUDIO_SINK@ $INC
eww poll volume
