#!/bin/sh

for folder in ~/Documents/Articles /Users/Stephen/Documents/Bibliographies,\ Booklists,\ Syllabi ~/Documents/CUA-MA ~/Documents/CUA-Teaching ~/Documents/Greek\ Authors:Texts ~/Documents/LEC ~/Documents/Latin\ Authors:Texts ~/Documents/Lexica:Ref ~/Documents/PDF\ Library ~/Documents/vimwiki_textastic ~/Documents/Programming\ Docs ~/Documents/SysAdmin\ Docs

do

find "$folder" -name 'temp[0-9]' -exec rm '{}' \;
find "$folder" ! -user www -exec sudo chown www '{}' \;
find "$folder" ! -group wheel -exec sudo chgrp wheel '{}' \;
find "$folder" -type d ! -perm 0775 -exec sudo chmod 0775 '{}' \;
find "$folder" -type f ! -perm 664 -exec sudo chmod 664 '{}' \;

done
