#!/bin/sh
# this script displays the contents of ~/.motd every 2 minutes in an osx notification
# ~/.motd is altered by 'start' and 'stop' alius set in .zshrc

interim=2;

tasktxt=`cat /Users/stephen/.motd`
echo "started $tasktxt"
while true; do
    ((minutes++)) || true
    sleep 60;
    if [[ $((${minutes} % $interim)) -eq 0 ]] ; then
      if [[ "$minutes" -eq 1 ]] ; then
        timetxt="1 minute"
      else
        timetxt="$minutes minutes"
      fi
      gecho -e "$timetxt" | chpst -u stephen terminal-notifier -title "$tasktxt" -group "sdb_timer";
    fi
done
